mapping = {
  "mappings": {
    "properties": {
       'id_cnefe': { "type": "match_only_text" },
            'cnefe_ano': { "type": "match_only_text" },
            'id_uf': { "type": "match_only_text" },
            'sg_uf': { "type": "match_only_text" },
            'id_municipio': { "type": "match_only_text" },
            'nm_municipio': { "type": "match_only_text" },
            'id_distrito': { "type": "match_only_text" },
            'id_subdistrito': { "type": "match_only_text" },
            'id_setor': { "type": "match_only_text" },
            'situacao_setor': { "type": "match_only_text" },
            'codigo_quadra': { "type": "match_only_text" },
            'codigo_face': { "type": "match_only_text" },
            'codigo_geo': { "type": "match_only_text" },
            'id_unico_endereco_ibge': { "type": "match_only_text" },
            'especie': { "type": "match_only_text" },
            'indicador_endereco': { "type": "match_only_text" },
            'logradouro': { "type": "text" },
            'tipo_logradouro': { "type": "match_only_text" },
            'titulo_logradouro': { "type": "match_only_text" },
            'nome_logradouro': { "type": "match_only_text" },
            'numero_imovel': { "type": "long"},
            'tipo_modificador': { "type": "match_only_text" },
            'nome_primeiro_complemento': { "type": "match_only_text" },
            'valor_primeiro_complemento': { "type": "match_only_text" },
            'nome_segundo_complemento': { "type": "match_only_text" },
            'valor_segundo_complemento': { "type": "match_only_text" },
            'nome_terceiro_complemento': { "type": "match_only_text" },
            'valor_terceiro_complemento': { "type": "match_only_text" },
            'nome_quarto_complemento': { "type": "match_only_text" },
            'valor_quarto_complemento': { "type": "match_only_text" },
            'nome_quinto_complemento': { "type": "match_only_text" },
            'valor_quinto_complemento': { "type": "match_only_text" },
            'dsc_ponto_referencia': { "type": "match_only_text" },
            'nome_localidade': { "type": "match_only_text" },
            'codigo_cep': { "type": "match_only_text" },
            'id_estabelecimento': { "type": "match_only_text" },
            'nome_estabelecimento': { "type": "match_only_text" },
            'cnefe_lat': { "type": "match_only_text" },
            'cnefe_lng': { "type": "match_only_text" },
            'altitude': { "type": "match_only_text" },
            'face_lat': { "type": "match_only_text" },
            'face_lng': { "type": "match_only_text" },
            'face_ano': { "type": "match_only_text" },
            'face_dist_max_estimada': { "type": "match_only_text" },
            'bgeo_lat': { "type": "match_only_text" },
            'bgeo_lng': { "type": "match_only_text" },
            'bgeo_dist_max_est': { "type": "match_only_text" },
            'bgeo_font': { "type": "match_only_text" },
            'id_localidade': { "type": "match_only_text" },
            'id_logradouro': { "type": "match_only_text" },
            'id_localidade_logradouro': { "type": "match_only_text" },
            'id_logradouro_numero':  { "type": "match_only_text" },
            'id_localidade_logradouro_numero': { "type": "match_only_text" },
            "coordenadas": {"type": "geo_point",
                           "ignore_malformed": "true"},
            'endereco': {"type": "text"},
            'endereco_completo': { "type": "text"}
    }
  }
}
